version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-api-dev
    restart: always
    ports:
      - "3000:3000"  # <-- Port 3000 kita buka kembali!
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
